# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a27b97ab8987b08a8be59633ca25060b1cf160365d607d981b21cd1fdcc66a671a33e44585adf2474441ee660e4e567e9bc653a061e69717c09b73afb79304

test:
  secret_key_base: 08d06e98e9902566b1ed9937c51311e98498451d13a8d9c991dff83d7402d22d2c53098c4f3bcab1af9b0446597ec70c4e68f887e911a2c110930e84c709ffcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
